"""
Fleet Commander Device Simulator

Simulates IoT devices that:
  - Register with the backend via MQTT
  - Send periodic heartbeats
  - Receive OTA commands and simulate the update lifecycle
  - Handle SHA256 hash mismatches with automatic rollback
  - Simulate EV battery behaviour for V2G (SOC, SOH, temp, plug status)
  - Respond to V2G discharge/charge commands
  - Simulate GPS location tracking with city assignment
"""

import asyncio
import json
import logging
import os
import random
import signal
import sys
import time
import uuid

import paho.mqtt.client as mqtt

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s: %(message)s")
logger = logging.getLogger("simulator")

MQTT_BROKER_HOST = os.environ.get("MQTT_BROKER_HOST", "localhost")
MQTT_BROKER_PORT = int(os.environ.get("MQTT_BROKER_PORT", 1883))
BACKEND_URL = os.environ.get("BACKEND_URL", "http://backend:8000")
DEVICE_COUNT = int(os.environ.get("SIMULATOR_DEVICE_COUNT", 15))
HEARTBEAT_INTERVAL = int(os.environ.get("SIMULATOR_HEARTBEAT_INTERVAL", 10))
OTA_FAILURE_RATE = float(os.environ.get("SIMULATOR_OTA_FAILURE_RATE", "0.2"))
INITIAL_FIRMWARE = "1.0.0"
GPS_FIRMWARE_VERSION = "2.0.0-gps"
GPS_INTERVAL = int(os.environ.get("SIMULATOR_GPS_INTERVAL", 30))
SIMULATOR_CITIES = os.environ.get("SIMULATOR_CITIES", "Bangalore,Mumbai,Delhi")

# ── P0 UC-24: mutual TLS to the production broker ───────────────────────────
# Each simulated device presents its OWN client certificate whose CN equals
# the device id (broker ACL: pattern write iot/fleet/%u/...). Certs are
# pre-generated by scripts/gen-mqtt-pki.sh into MQTT_CLIENT_CERT_DIR as
# <device_id>.crt / <device_id>.key.
MQTT_TLS = os.environ.get("MQTT_TLS", "0").lower() in ("1", "true", "yes")
MQTT_CA_CERT = os.environ.get("MQTT_CA_CERT", "/app/certs/ca.crt")
MQTT_CLIENT_CERT_DIR = os.environ.get("MQTT_CLIENT_CERT_DIR", "/app/certs/simulator")
# Force stable ids matching cert CNs in TLS mode (comma-separated).
SIMULATOR_DEVICE_IDS = [d.strip() for d in os.environ.get("SIMULATOR_DEVICE_IDS", "").split(",") if d.strip()]

V2G_POWER_KW = 7.2
BATTERY_CAPACITY_KWH = 60.0

# ── MVP DATA-01: OBD-grade telemetry + fault injection ───────────────────────
# SIMULATOR_OBD=1 adds source/fuel/odometer/tire/DTC fields to every heartbeat.
# SIMULATOR_SCENARIO=drift|thermal|tpms arms a fault progression on the device
# at SIMULATOR_FAULT_DEVICE_INDEX (0-based). The progression is the eval
# harness's ground truth (see tests/test_ml_eval.py + tests/eval_thresholds.yml).
SIMULATOR_OBD = os.environ.get("SIMULATOR_OBD", "1").lower() in ("1", "true", "yes")
SIMULATOR_SCENARIO = os.environ.get("SIMULATOR_SCENARIO", "none").lower()
SIMULATOR_FAULT_DEVICE_INDEX = int(os.environ.get("SIMULATOR_FAULT_DEVICE_INDEX", "0"))
# SRS Idea 4: cargo telemetry (bay climate + door + IMU) + drop injection.
SIMULATOR_CARGO = os.environ.get("SIMULATOR_CARGO", "1").lower() in ("1", "true", "yes")
SIMULATOR_CARGO_DROP = os.environ.get("SIMULATOR_CARGO_DROP", "0").lower() in ("1", "true", "yes")
# Fault DTCs asserted once the progression crosses its threshold.
SCENARIO_DTC = {"drift": ["U0100"], "thermal": ["P0128"], "tpms": ["C0745"]}
NOMINAL_TIRE_PSI = 32.0

CITY_COORDS = {
    "Bangalore": (12.9716, 77.5946),
    "Mumbai": (19.0760, 72.8777),
    "Delhi": (28.7041, 77.1025),
    "Chennai": (13.0827, 80.2707),
    "Hyderabad": (17.3850, 78.4867),
    "Pune": (18.5204, 73.8567),
    "Kolkata": (22.5726, 88.3639),
    "Ahmedabad": (23.0225, 72.5714),
}


# Vehicle profiles cycled across simulated devices (make, model, year span, EV?).
VEHICLE_PROFILES = [
    ("Tata", "Nexon EV", 2023, True),
    ("Mahindra", "XUV400", 2023, True),
    ("Tata", "Ace EV", 2022, True),
    ("Ashok Leyland", "Dost", 2021, False),
    ("Maruti", "Super Carry", 2022, False),
    ("Tata", "Intra V30", 2021, False),
]
CELL_COUNT = 96
CELL_NOMINAL_V = 4.10


def make_vin(index: int) -> str:
    """Deterministic 17-char demo VIN (MAT prefix + zero-padded index + check)."""
    base = f"MAT6242{index:05d}P"
    check = str((sum(ord(c) * (i + 1) for i, c in enumerate(base)) + index) % 10)
    return (base + check + "X").ljust(17, "0")[:17]


class SimulatedDevice:
    def __init__(self, device_id: str, name: str, city: str = "Bangalore", is_ev: bool = False,
                 profile_idx: int = 0):
        self.id = device_id
        self.name = name
        self.firmware_version = INITIAL_FIRMWARE
        self.previous_firmware = INITIAL_FIRMWARE
        self.status = "offline"
        self.signal_strength = random.randint(-90, -40)
        self.uptime = 100.0
        self.start_time = time.time()

        # GPS / location tracking
        self.city = city
        base_lat, base_lng = CITY_COORDS.get(city, (12.9716, 77.5946))
        self.latitude = base_lat + random.uniform(-0.015, 0.015)
        self.longitude = base_lng + random.uniform(-0.015, 0.015)
        self.gps_active = False
        self.last_gps_time = 0.0

        # EV battery simulation
        self.is_ev = is_ev
        self.soc = 80.0  # percent
        self.soh = 100.0  # percent
        self.battery_temp = 25.0  # celsius
        self.plug_status = "connected"
        self._v2g_action = "idle"
        self._v2g_end_time = 0.0
        self._in_maintenance = False
        # Simulated resource metrics (Feature 1 telemetry)
        self.cpu_usage = random.uniform(5, 25)
        self.memory_usage = random.uniform(30, 55)
        self.temperature = random.uniform(35, 55)

        # MVP DATA-01: OBD-grade state
        self.fuel_level_pct = random.uniform(40, 90)
        self.odometer_km = random.uniform(5000, 80000)
        self.tire_pressures = {k: round(random.uniform(31.0, 33.0), 1) for k in ("fl", "fr", "rl", "rr")}
        self.dtc_codes: list = []
        self.scenario = "none"
        self._fault_step = 0

        # SRS Idea 4: cargo bay climate + door + IMU handling state.
        self.bay_temp_c = random.uniform(2.5, 3.5)
        self.humidity_pct = random.uniform(60, 75)
        self.door_open = False
        self.shock_g = 0.2  # latest peak-g in window
        self._drop_armed = False

        # Vehicle identity + EV cell model (OBD simulator)
        make, model, year, profile_ev = VEHICLE_PROFILES[profile_idx % len(VEHICLE_PROFILES)]
        self.make = make
        self.model = model
        self.model_year = year + (profile_idx // len(VEHICLE_PROFILES)) % 3
        if profile_ev:
            self.is_ev = True
        self.vin = make_vin(abs(hash(device_id)) % 100000)
        self.cell_voltages = [round(random.uniform(4.05, 4.15), 3) for _ in range(CELL_COUNT)]
        self.rpm = random.uniform(800, 1200)
        self.speed_kph = 0.0
        self._client = mqtt.Client(
            client_id=f"sim-{device_id[:8]}",
            protocol=mqtt.MQTTv5,
            callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
        )
        self._client.on_connect = self._on_connect
        self._client.on_message = self._on_message
        self._connected = False
        self._running = False

    def _on_connect(self, client, userdata, flags, reason_code, properties=None):
        if reason_code == 0:
            logger.info(f"[{self.name}] Connected to MQTT broker")
            self._connected = True
            topic = f"iot/fleet/{self.id}/command/ota"
            client.subscribe(topic, qos=1)
            config_topic = f"iot/fleet/{self.id}/command/config"
            client.subscribe(config_topic, qos=1)
            v2g_topic = f"iot/fleet/{self.id}/command/v2g"
            client.subscribe(v2g_topic, qos=1)
            # Feature 5/7/9: subscribe to new command topics
            client.subscribe(f"iot/fleet/{self.id}/command/restart", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/rollback", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/maintenance", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/shadow", qos=1)
        else:
            logger.error(f"[{self.name}] MQTT connection failed: rc={reason_code}")

    def _on_message(self, client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode())
            if msg.topic.endswith("/command/ota"):
                logger.info(f"[{self.name}] Received OTA command: {payload.get('firmware_url', '')}")
                asyncio.run_coroutine_threadsafe(
                    self._handle_ota_command(payload), self._loop
                )
            elif msg.topic.endswith("/command/config"):
                logger.info(f"[{self.name}] Received remote config: {payload.get('config', {})}")
                self._handle_config_command(payload)
            elif msg.topic.endswith("/command/v2g"):
                logger.info(f"[{self.name}] Received V2G command: {payload.get('action', '')}")
                self._handle_v2g_command(payload)
            elif msg.topic.endswith("/command/restart"):
                logger.info(f"[{self.name}] Received restart command: {payload.get('reason', '')}")
                self._handle_restart_command(payload)
            elif msg.topic.endswith("/command/rollback"):
                logger.info(f"[{self.name}] Received rollback command")
                self._handle_rollback_command(payload)
            elif msg.topic.endswith("/command/maintenance"):
                logger.info(f"[{self.name}] Received maintenance command: {payload.get('command', '')}")
                self._handle_maintenance_command(payload)
            elif msg.topic.endswith("/command/shadow"):
                logger.info(f"[{self.name}] Received shadow desired state")
                self._handle_shadow_command(payload)
        except Exception as e:
            logger.error(f"[{self.name}] Error processing command: {e}")

    def _handle_config_command(self, payload: dict):
        config = payload.get("config", {})
        if "heartbeat_interval_seconds" in config:
            global HEARTBEAT_INTERVAL
            # Per-device would be better, but for the simulator this is a demo
            logger.info(f"[{self.name}] Config update: heartbeat={config.get('heartbeat_interval_seconds')}")

    def _handle_restart_command(self, payload: dict):
        logger.info(f"[{self.name}] Soft restart: {payload.get('reason', 'unknown')}")
        self.start_time = time.time()
        self.uptime = 100.0

    def _handle_rollback_command(self, payload: dict):
        prev_fw = payload.get("previous_firmware", self.previous_firmware)
        logger.info(f"[{self.name}] Rolling back firmware to {prev_fw}")
        self.firmware_version = prev_fw

    def _handle_maintenance_command(self, payload: dict):
        cmd = payload.get("command", "")
        reason = payload.get("reason", "")
        if cmd == "enter_maintenance":
            logger.info(f"[{self.name}] Entering maintenance mode: {reason}")
            self._in_maintenance = True
        elif cmd == "exit_maintenance":
            logger.info(f"[{self.name}] Exiting maintenance mode: {reason}")
            self._in_maintenance = False

    def _handle_shadow_command(self, payload: dict):
        state = payload.get("state", {})
        logger.info(f"[{self.name}] Shadow desired state received: {list(state.keys())}")
        # Publish reported state back (Feature 7)
        reported = {
            "action": "idle",
            "soc": round(self.soc, 1) if self.is_ev else None,
            "soh": round(self.soh, 1) if self.is_ev else None,
            "firmware_version": self.firmware_version,
            "signal_strength": self.signal_strength,
        }
        topic = f"iot/fleet/{self.id}/status/v2g"
        self._client.publish(topic, json.dumps(reported), qos=1)

    async def _handle_ota_command(self, payload: dict):
        firmware_url = payload.get("firmware_url", "")
        expected_hash = payload.get("sha256_hash", "")
        deployment_id = payload.get("deployment_id", str(uuid.uuid4()))

        logger.info(f"[{self.name}] Starting OTA: {firmware_url}")

        await self._publish_ota_status("downloading", deployment_id)
        await asyncio.sleep(random.uniform(1.0, 3.0))

        await self._publish_ota_status("applying", deployment_id)
        await asyncio.sleep(random.uniform(1.0, 2.0))

        await self._publish_ota_status("verifying", deployment_id)
        await asyncio.sleep(random.uniform(0.5, 1.5))

        # Simulate OTA failure/rollback based on failure rate
        if random.random() < OTA_FAILURE_RATE:
            logger.warning(f"[{self.name}] SHA256 hash mismatch! Rolling back.")
            await self._publish_ota_status("hash_mismatch", deployment_id, error="SHA256 hash mismatch")
            await asyncio.sleep(0.5)
            await self._publish_ota_status("rollback", deployment_id)
            await asyncio.sleep(1.0)
            self.firmware_version = self.previous_firmware
            await self._publish_ota_status("rolled_back", deployment_id)
        else:
            self.previous_firmware = self.firmware_version
            self.firmware_version = payload.get("new_version", self.firmware_version)
            await self._publish_ota_status("success", deployment_id)
            logger.info(f"[{self.name}] OTA success, firmware: {self.firmware_version}")

    async def _publish_ota_status(self, status: str, deployment_id: str, error: str = None):
        payload = {
            "status": status,
            "deployment_id": deployment_id,
            "device_id": self.id,
            "timestamp": time.time(),
        }
        if error:
            payload["error"] = error
        topic = f"iot/fleet/{self.id}/status/ota"
        result = self._client.publish(topic, json.dumps(payload), qos=1)
        if result.rc != 0:
            logger.warning(f"[{self.name}] Failed to publish OTA status: {status}")

    def _handle_v2g_command(self, payload: dict):
        action = payload.get("action", "idle")
        power_kw = float(payload.get("power_kw", V2G_POWER_KW))
        duration_min = int(payload.get("duration_minutes", 60))
        self._v2g_action = action
        self._v2g_end_time = time.time() + duration_min * 60
        if action == "discharge":
            self.plug_status = "discharging"
            logger.info(f"[{self.name}] V2G discharging at {power_kw}kW for {duration_min}min")
        elif action == "charge":
            self.plug_status = "charging"
            logger.info(f"[{self.name}] V2G charging at {power_kw}kW for {duration_min}min")
        else:
            self.plug_status = "connected"
            self._v2g_action = "idle"

    def _update_battery(self):
        if not self.is_ev:
            return
        now = time.time()
        # Temperature cycles slowly
        self.battery_temp += random.uniform(-0.5, 0.5)
        self.battery_temp = max(15.0, min(45.0, self.battery_temp))

        if self._v2g_action == "discharge" and now < self._v2g_end_time:
            discharge_kwh = V2G_POWER_KW * (HEARTBEAT_INTERVAL / 3600.0)
            soc_drop = (discharge_kwh / BATTERY_CAPACITY_KWH) * 100.0
            self.soc = max(10.0, self.soc - soc_drop)
            self.battery_temp += 0.2  # heat from discharge
        elif self._v2g_action == "charge" and now < self._v2g_end_time:
            charge_kwh = V2G_POWER_KW * (HEARTBEAT_INTERVAL / 3600.0)
            soc_rise = (charge_kwh / BATTERY_CAPACITY_KWH) * 100.0
            self.soc = min(95.0, self.soc + soc_rise)
            self.battery_temp += 0.1
        else:
            self._v2g_action = "idle"
            self.plug_status = "connected"
            # Slow self-discharge when idle
            self.soc = max(10.0, self.soc - 0.01)

        # SOH slowly degrades over time
        self.soh = max(70.0, self.soh - 0.001)

        # Cell voltages drift with SOC + noise; thermal fault spreads the pack.
        spread = 0.03 if self.scenario != "thermal" else min(0.25, 0.03 + self._fault_step * 0.01)
        base = 3.6 + (self.soc / 100.0) * 0.55
        self.cell_voltages = [round(base + random.uniform(-spread, spread), 3)
                              for _ in range(CELL_COUNT)]

    def _update_fault(self):
        """MVP DATA-01: advance the armed fault scenario one heartbeat step.

        Each scenario starts nominal and degrades monotonically so the eval
        harness can measure detection + lead time against a known onset
        (fault step 0 == first degraded heartbeat).
        """
        if self.scenario == "none":
            self.dtc_codes = []
            return
        self._fault_step += 1
        if self.scenario == "drift":
            # Antenna degradation: signal falls ~1.5 dBm/beat into the noise floor.
            self.signal_strength = max(-100, self.signal_strength - random.uniform(1.0, 2.0))
            if self.signal_strength < -85:
                self.dtc_codes = list(SCENARIO_DTC["drift"])
        elif self.scenario == "thermal":
            # Cooling failure: temperature climbs ~0.9 C/beat past safe limits.
            self.temperature = min(96.0, self.temperature + random.uniform(0.7, 1.1))
            if self.is_ev:
                self.battery_temp = min(70.0, self.battery_temp + random.uniform(0.4, 0.7))
            if self.temperature > 75:
                self.dtc_codes = list(SCENARIO_DTC["thermal"])
        elif self.scenario == "tpms":
            # Slow puncture on rear-right tire.
            self.tire_pressures["rr"] = round(max(20.0, self.tire_pressures["rr"] - 0.15), 1)
            if self.tire_pressures["rr"] < 28.0:
                self.dtc_codes = list(SCENARIO_DTC["tpms"])

    def _update_obd(self):
        """MVP DATA-01: nominal OBD-grade drift (fuel burn, mileage)."""
        self.fuel_level_pct = max(0.0, self.fuel_level_pct - 0.02)
        self.odometer_km += 0.05

    def _update_resources(self):
        """Simulate CPU/memory/temperature drift for telemetry (Feature 1)."""
        self.cpu_usage = max(1.0, min(95.0, self.cpu_usage + random.uniform(-2, 2)))
        self.memory_usage = max(10.0, min(90.0, self.memory_usage + random.uniform(-1, 1)))
        self.temperature = max(20.0, min(85.0, self.temperature + random.uniform(-0.5, 0.5)))
        # Correlate temperature with CPU load
        if self.cpu_usage > 70:
            self.temperature += 0.5

    def _update_gps(self):
        now = time.time()
        if not self.gps_active and (now - self.start_time) >= GPS_INTERVAL:
            self.gps_active = True
            self.firmware_version = GPS_FIRMWARE_VERSION
            self.last_gps_time = now
            logger.info(f"[{self.name}] GPS activated, firmware -> {GPS_FIRMWARE_VERSION}")
        if self.gps_active and (now - self.last_gps_time) >= GPS_INTERVAL:
            self.latitude += random.uniform(-0.0005, 0.0005)
            self.longitude += random.uniform(-0.0005, 0.0005)
            self.last_gps_time = now

    async def register(self):
        payload = json.dumps({
            "device_id": self.id,
            "name": self.name,
            "firmware_version": self.firmware_version,
            "ip_address": f"10.0.0.{random.randint(1, 254)}",
            "city": self.city,
            "vin": self.vin,
            "make": self.make,
            "model": self.model,
            "model_year": self.model_year,
        })
        # P0 UC-25 JITP: per-device topic — broker ACL binds this topic to the
        # client cert CN, giving the backend a verified identity. The legacy
        # shared topic remains only for the anonymous demo profile.
        self._client.publish(f"iot/fleet/{self.id}/register", payload, qos=1)
        if not MQTT_TLS:
            self._client.publish("iot/fleet/register", payload, qos=1)
        self.status = "online"
        logger.info(f"[{self.name}] Registered (fw={self.firmware_version}, city={self.city})")

    async def send_heartbeat(self):
        if self._in_maintenance:
            return  # Skip heartbeats while in maintenance mode (Feature 9)
        self.uptime = min(100.0, 100.0 * (1.0 - (time.time() - self.start_time) / 86400) + 95.0)
        self.signal_strength = random.randint(max(-95, self.signal_strength - 2), min(-30, self.signal_strength + 2))
        # Driving cycle: cruise segments with RPM/speed, parked otherwise.
        cruising = (int(time.time() / HEARTBEAT_INTERVAL) % 6) < 4
        self.speed_kph = round(random.uniform(35, 65), 1) if cruising else 0.0
        self.rpm = round(random.uniform(1400, 2200) if cruising else random.uniform(750, 900), 0)
        self._update_battery()
        self._update_gps()
        self._update_resources()
        self._update_obd()
        self._update_fault()

        now_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        payload = {
            "uptime_percentage": round(self.uptime, 1),
            "signal_strength": self.signal_strength,
            "firmware_version": self.firmware_version,
            "city": self.city,
            "cpu_usage": round(self.cpu_usage, 1),
            "memory_usage": round(self.memory_usage, 1),
            "temperature": round(self.temperature, 1),
        }
        if SIMULATOR_OBD:
            payload["source"] = "obd"
            payload["fuel_level_pct"] = round(self.fuel_level_pct, 1)
            payload["odometer_km"] = round(self.odometer_km, 1)
            payload["tire_pressures"] = dict(self.tire_pressures)
            if self.dtc_codes:
                payload["dtc_codes"] = list(self.dtc_codes)
        if self.is_ev:
            payload["soc"] = round(self.soc, 1)
            payload["soh"] = round(self.soh, 1)
            payload["battery_temp"] = round(self.battery_temp, 1)
            payload["plug_status"] = self.plug_status
        if self.gps_active:
            payload["latitude"] = round(self.latitude, 6)
            payload["longitude"] = round(self.longitude, 6)

        topic = f"iot/fleet/{self.id}/heartbeat"
        self._client.publish(topic, json.dumps(payload), qos=1)
        self._publish_obd(now_iso)
        if self.is_ev:
            self._publish_bms(now_iso)
        self._publish_cargo(now_iso)

    def _publish_cargo(self, now_iso: str):
        """SRS Idea 4: cargo telemetry with edge ai_inference stub block."""
        if not SIMULATOR_CARGO:
            return
        # Bay climate random-walks around the cold-chain band; door blips rare.
        self.bay_temp_c = max(-5.0, min(15.0, self.bay_temp_c + random.uniform(-0.3, 0.3)))
        self.humidity_pct = max(20.0, min(95.0, self.humidity_pct + random.uniform(-1, 1)))
        if random.random() < 0.02:
            self.door_open = not self.door_open
        # IMU: background road noise; scripted HARD_DROP when armed.
        if SIMULATOR_CARGO_DROP and not self._drop_armed and random.random() < 0.1:
            self._drop_armed = True
            self.shock_g = round(random.uniform(6.0, 9.0), 1)
        else:
            self.shock_g = round(random.uniform(0.1, 0.8), 2)
        tts = max(0.0, (4.0 - self.bay_temp_c) * 45.0)  # stub slope model
        cargo = {
            "event_time": now_iso,
            "source": "sim",
            "device_id": self.id,
            "sensors": {
                "temperature_celsius": round(self.bay_temp_c, 1),
                "humidity_pct": round(self.humidity_pct, 1),
                "door_open": self.door_open,
            },
            "shock_g": self.shock_g,
            "ai_inference": {
                "spoilage_risk_level": "HIGH" if tts < 60 else ("MEDIUM" if tts < 180 else "LOW"),
                "predicted_tts_minutes": round(tts, 1),
                "last_impact_event": "HARD_DROP" if self._drop_armed and self.shock_g > 5 else "NORMAL_ROAD_BUMP",
            },
        }
        self._client.publish(f"iot/fleet/{self.id}/cargo", json.dumps(cargo), qos=1)
        self._drop_armed = False

    def _publish_obd(self, now_iso: str):
        """OBD-II gateway feed: PID map + vehicle identity + OBD state."""
        if not SIMULATOR_OBD:
            return
        obd = {
            "event_time": now_iso,
            "source": "obd",
            "vin": self.vin,
            "odometer_km": round(self.odometer_km, 1),
            "fuel_level_pct": round(self.fuel_level_pct, 1),
            "dtc_codes": list(self.dtc_codes),
            "tire_pressures": dict(self.tire_pressures),
            "pid_map": {
                "rpm": self.rpm,
                "speed_kph": self.speed_kph,
                "coolant_c": round(self.temperature - 8.0, 1),
                "maf_gs": round(2.0 + self.rpm / 1000.0, 2),
            },
        }
        self._client.publish(f"iot/fleet/{self.id}/obd", json.dumps(obd), qos=1)

    def _publish_bms(self, now_iso: str):
        """BMS feed for EVs: pack state + full cell-voltage array."""
        cells = self.cell_voltages
        bms = {
            "event_time": now_iso,
            "source": "bms",
            "soc": round(self.soc, 1),
            "soh": round(self.soh, 1),
            "pack_temp": round(self.battery_temp, 1),
            "plug_status": self.plug_status,
            "cell_voltages": cells,
            "cell_min_v": min(cells),
            "cell_max_v": max(cells),
            "cell_count": len(cells),
        }
        self._client.publish(f"iot/fleet/{self.id}/bms", json.dumps(bms), qos=1)

    def connect(self, loop: asyncio.AbstractEventLoop):
        self._loop = loop
        self._client.reconnect_delay_set(min_delay=1, max_delay=60)
        if MQTT_TLS:
            import ssl
            cert_file = os.path.join(MQTT_CLIENT_CERT_DIR, f"{self.id}.crt")
            key_file = os.path.join(MQTT_CLIENT_CERT_DIR, f"{self.id}.key")
            self._client.tls_set(
                ca_certs=MQTT_CA_CERT,
                certfile=cert_file,
                keyfile=key_file,
                tls_version=ssl.PROTOCOL_TLS_CLIENT,
            )
            logger.info(f"[{self.name}] TLS enabled (cert={cert_file})")
        self._client.connect(MQTT_BROKER_HOST, MQTT_BROKER_PORT, keepalive=60)
        self._client.loop_start()

    def disconnect(self):
        self._running = False
        self._client.loop_stop()
        self._client.disconnect()

    async def register_with_retry(self, retries=3, gap=3):
        for attempt in range(retries):
            if attempt > 0:
                await asyncio.sleep(gap)
            await self.register()

    async def run(self):
        self._running = True
        self.connect(asyncio.get_event_loop())
        await self.register_with_retry()

        while self._running:
            await asyncio.sleep(HEARTBEAT_INTERVAL)
            await self.send_heartbeat()

        self.disconnect()


async def main():
    logger.info(f"Starting device simulator with {DEVICE_COUNT} devices (tls={MQTT_TLS})")
    city_list = [c.strip() for c in SIMULATOR_CITIES.split(",") if c.strip()]
    if not city_list:
        city_list = ["Bangalore"]
    logger.info(f"City pool: {city_list}, GPS interval: {GPS_INTERVAL}s")
    devices = []

    for i in range(DEVICE_COUNT):
        # P0 UC-24: in TLS mode ids must equal cert CNs (sim-001, sim-002, …).
        if i < len(SIMULATOR_DEVICE_IDS):
            device_id = SIMULATOR_DEVICE_IDS[i]
        elif MQTT_TLS:
            device_id = f"sim-{i+1:03d}"
        else:
            device_id = str(uuid.uuid4())
        is_ev = i < 3  # first 3 devices are EVs with battery simulation
        name = f"Device-{i+1:03d}"
        city = city_list[i % len(city_list)]
        device = SimulatedDevice(device_id, name, city=city, is_ev=is_ev, profile_idx=i)
        # MVP DATA-01: arm the fault scenario on one device (eval ground truth).
        if SIMULATOR_SCENARIO in ("drift", "thermal", "tpms") and i == SIMULATOR_FAULT_DEVICE_INDEX:
            device.scenario = SIMULATOR_SCENARIO
            logger.info(f"Fault scenario '{SIMULATOR_SCENARIO}' armed on {name}")
        devices.append(device)
        asyncio.create_task(device.run())
        logger.info(f"Created simulated device: {name} ({device_id}) city={city} is_ev={is_ev}")

    def shutdown():
        logger.info("Shutting down simulator...")
        for d in devices:
            d.disconnect()

    loop = asyncio.get_event_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, shutdown)
        except NotImplementedError:
            pass

    try:
        await asyncio.Event().wait()
    except asyncio.CancelledError:
        shutdown()


if __name__ == "__main__":
    asyncio.run(main())
