"""
Fleet Commander Device Simulator

Simulates IoT devices that:
  - Register with the backend via MQTT
  - Send periodic heartbeats
  - Receive OTA commands and simulate the update lifecycle
  - Handle SHA256 hash mismatches with automatic rollback
  - Simulate EV battery behaviour for V2G (SOC, SOH, temp, plug status)
  - Respond to V2G discharge/charge commands
  - Simulate GPS location tracking with city assignment
"""

import asyncio
import json
import logging
import os
import random
import signal
import sys
import time
import uuid

import paho.mqtt.client as mqtt

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s: %(message)s")
logger = logging.getLogger("simulator")

MQTT_BROKER_HOST = os.environ.get("MQTT_BROKER_HOST", "localhost")
MQTT_BROKER_PORT = int(os.environ.get("MQTT_BROKER_PORT", 1883))
BACKEND_URL = os.environ.get("BACKEND_URL", "http://backend:8000")
DEVICE_COUNT = int(os.environ.get("SIMULATOR_DEVICE_COUNT", 15))
HEARTBEAT_INTERVAL = int(os.environ.get("SIMULATOR_HEARTBEAT_INTERVAL", 10))
OTA_FAILURE_RATE = float(os.environ.get("SIMULATOR_OTA_FAILURE_RATE", "0.2"))
INITIAL_FIRMWARE = "1.0.0"
GPS_FIRMWARE_VERSION = "2.0.0-gps"
GPS_INTERVAL = int(os.environ.get("SIMULATOR_GPS_INTERVAL", 30))
SIMULATOR_CITIES = os.environ.get("SIMULATOR_CITIES", "Bangalore,Mumbai,Delhi")

# ── P0 UC-24: mutual TLS to the production broker ───────────────────────────
# Each simulated device presents its OWN client certificate whose CN equals
# the device id (broker ACL: pattern write iot/fleet/%u/...). Certs are
# pre-generated by scripts/gen-mqtt-pki.sh into MQTT_CLIENT_CERT_DIR as
# <device_id>.crt / <device_id>.key.
MQTT_TLS = os.environ.get("MQTT_TLS", "0").lower() in ("1", "true", "yes")
MQTT_CA_CERT = os.environ.get("MQTT_CA_CERT", "/app/certs/ca.crt")
MQTT_CLIENT_CERT_DIR = os.environ.get("MQTT_CLIENT_CERT_DIR", "/app/certs/simulator")
# Force stable ids matching cert CNs in TLS mode (comma-separated).
SIMULATOR_DEVICE_IDS = [d.strip() for d in os.environ.get("SIMULATOR_DEVICE_IDS", "").split(",") if d.strip()]

V2G_POWER_KW = 7.2
BATTERY_CAPACITY_KWH = 60.0

CITY_COORDS = {
    "Bangalore": (12.9716, 77.5946),
    "Mumbai": (19.0760, 72.8777),
    "Delhi": (28.7041, 77.1025),
    "Chennai": (13.0827, 80.2707),
    "Hyderabad": (17.3850, 78.4867),
    "Pune": (18.5204, 73.8567),
    "Kolkata": (22.5726, 88.3639),
    "Ahmedabad": (23.0225, 72.5714),
}


class SimulatedDevice:
    def __init__(self, device_id: str, name: str, city: str = "Bangalore", is_ev: bool = False):
        self.id = device_id
        self.name = name
        self.firmware_version = INITIAL_FIRMWARE
        self.previous_firmware = INITIAL_FIRMWARE
        self.status = "offline"
        self.signal_strength = random.randint(-90, -40)
        self.uptime = 100.0
        self.start_time = time.time()

        # GPS / location tracking
        self.city = city
        base_lat, base_lng = CITY_COORDS.get(city, (12.9716, 77.5946))
        self.latitude = base_lat + random.uniform(-0.015, 0.015)
        self.longitude = base_lng + random.uniform(-0.015, 0.015)
        self.gps_active = False
        self.last_gps_time = 0.0

        # EV battery simulation
        self.is_ev = is_ev
        self.soc = 80.0  # percent
        self.soh = 100.0  # percent
        self.battery_temp = 25.0  # celsius
        self.plug_status = "connected"
        self._v2g_action = "idle"
        self._v2g_end_time = 0.0
        self._in_maintenance = False
        # Simulated resource metrics (Feature 1 telemetry)
        self.cpu_usage = random.uniform(5, 25)
        self.memory_usage = random.uniform(30, 55)
        self.temperature = random.uniform(35, 55)

        self._client = mqtt.Client(
            client_id=f"sim-{device_id[:8]}",
            protocol=mqtt.MQTTv5,
            callback_api_version=mqtt.CallbackAPIVersion.VERSION2,
        )
        self._client.on_connect = self._on_connect
        self._client.on_message = self._on_message
        self._connected = False
        self._running = False

    def _on_connect(self, client, userdata, flags, reason_code, properties=None):
        if reason_code == 0:
            logger.info(f"[{self.name}] Connected to MQTT broker")
            self._connected = True
            topic = f"iot/fleet/{self.id}/command/ota"
            client.subscribe(topic, qos=1)
            config_topic = f"iot/fleet/{self.id}/command/config"
            client.subscribe(config_topic, qos=1)
            v2g_topic = f"iot/fleet/{self.id}/command/v2g"
            client.subscribe(v2g_topic, qos=1)
            # Feature 5/7/9: subscribe to new command topics
            client.subscribe(f"iot/fleet/{self.id}/command/restart", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/rollback", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/maintenance", qos=1)
            client.subscribe(f"iot/fleet/{self.id}/command/shadow", qos=1)
        else:
            logger.error(f"[{self.name}] MQTT connection failed: rc={reason_code}")

    def _on_message(self, client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode())
            if msg.topic.endswith("/command/ota"):
                logger.info(f"[{self.name}] Received OTA command: {payload.get('firmware_url', '')}")
                asyncio.run_coroutine_threadsafe(
                    self._handle_ota_command(payload), self._loop
                )
            elif msg.topic.endswith("/command/config"):
                logger.info(f"[{self.name}] Received remote config: {payload.get('config', {})}")
                self._handle_config_command(payload)
            elif msg.topic.endswith("/command/v2g"):
                logger.info(f"[{self.name}] Received V2G command: {payload.get('action', '')}")
                self._handle_v2g_command(payload)
            elif msg.topic.endswith("/command/restart"):
                logger.info(f"[{self.name}] Received restart command: {payload.get('reason', '')}")
                self._handle_restart_command(payload)
            elif msg.topic.endswith("/command/rollback"):
                logger.info(f"[{self.name}] Received rollback command")
                self._handle_rollback_command(payload)
            elif msg.topic.endswith("/command/maintenance"):
                logger.info(f"[{self.name}] Received maintenance command: {payload.get('command', '')}")
                self._handle_maintenance_command(payload)
            elif msg.topic.endswith("/command/shadow"):
                logger.info(f"[{self.name}] Received shadow desired state")
                self._handle_shadow_command(payload)
        except Exception as e:
            logger.error(f"[{self.name}] Error processing command: {e}")

    def _handle_config_command(self, payload: dict):
        config = payload.get("config", {})
        if "heartbeat_interval_seconds" in config:
            global HEARTBEAT_INTERVAL
            # Per-device would be better, but for the simulator this is a demo
            logger.info(f"[{self.name}] Config update: heartbeat={config.get('heartbeat_interval_seconds')}")

    def _handle_restart_command(self, payload: dict):
        logger.info(f"[{self.name}] Soft restart: {payload.get('reason', 'unknown')}")
        self.start_time = time.time()
        self.uptime = 100.0

    def _handle_rollback_command(self, payload: dict):
        prev_fw = payload.get("previous_firmware", self.previous_firmware)
        logger.info(f"[{self.name}] Rolling back firmware to {prev_fw}")
        self.firmware_version = prev_fw

    def _handle_maintenance_command(self, payload: dict):
        cmd = payload.get("command", "")
        reason = payload.get("reason", "")
        if cmd == "enter_maintenance":
            logger.info(f"[{self.name}] Entering maintenance mode: {reason}")
            self._in_maintenance = True
        elif cmd == "exit_maintenance":
            logger.info(f"[{self.name}] Exiting maintenance mode: {reason}")
            self._in_maintenance = False

    def _handle_shadow_command(self, payload: dict):
        state = payload.get("state", {})
        logger.info(f"[{self.name}] Shadow desired state received: {list(state.keys())}")
        # Publish reported state back (Feature 7)
        reported = {
            "action": "idle",
            "soc": round(self.soc, 1) if self.is_ev else None,
            "soh": round(self.soh, 1) if self.is_ev else None,
            "firmware_version": self.firmware_version,
            "signal_strength": self.signal_strength,
        }
        topic = f"iot/fleet/{self.id}/status/v2g"
        self._client.publish(topic, json.dumps(reported), qos=1)

    async def _handle_ota_command(self, payload: dict):
        firmware_url = payload.get("firmware_url", "")
        expected_hash = payload.get("sha256_hash", "")
        deployment_id = payload.get("deployment_id", str(uuid.uuid4()))

        logger.info(f"[{self.name}] Starting OTA: {firmware_url}")

        await self._publish_ota_status("downloading", deployment_id)
        await asyncio.sleep(random.uniform(1.0, 3.0))

        await self._publish_ota_status("applying", deployment_id)
        await asyncio.sleep(random.uniform(1.0, 2.0))

        await self._publish_ota_status("verifying", deployment_id)
        await asyncio.sleep(random.uniform(0.5, 1.5))

        # Simulate OTA failure/rollback based on failure rate
        if random.random() < OTA_FAILURE_RATE:
            logger.warning(f"[{self.name}] SHA256 hash mismatch! Rolling back.")
            await self._publish_ota_status("hash_mismatch", deployment_id, error="SHA256 hash mismatch")
            await asyncio.sleep(0.5)
            await self._publish_ota_status("rollback", deployment_id)
            await asyncio.sleep(1.0)
            self.firmware_version = self.previous_firmware
            await self._publish_ota_status("rolled_back", deployment_id)
        else:
            self.previous_firmware = self.firmware_version
            self.firmware_version = payload.get("new_version", self.firmware_version)
            await self._publish_ota_status("success", deployment_id)
            logger.info(f"[{self.name}] OTA success, firmware: {self.firmware_version}")

    async def _publish_ota_status(self, status: str, deployment_id: str, error: str = None):
        payload = {
            "status": status,
            "deployment_id": deployment_id,
            "device_id": self.id,
            "timestamp": time.time(),
        }
        if error:
            payload["error"] = error
        topic = f"iot/fleet/{self.id}/status/ota"
        result = self._client.publish(topic, json.dumps(payload), qos=1)
        if result.rc != 0:
            logger.warning(f"[{self.name}] Failed to publish OTA status: {status}")

    def _handle_v2g_command(self, payload: dict):
        action = payload.get("action", "idle")
        power_kw = float(payload.get("power_kw", V2G_POWER_KW))
        duration_min = int(payload.get("duration_minutes", 60))
        self._v2g_action = action
        self._v2g_end_time = time.time() + duration_min * 60
        if action == "discharge":
            self.plug_status = "discharging"
            logger.info(f"[{self.name}] V2G discharging at {power_kw}kW for {duration_min}min")
        elif action == "charge":
            self.plug_status = "charging"
            logger.info(f"[{self.name}] V2G charging at {power_kw}kW for {duration_min}min")
        else:
            self.plug_status = "connected"
            self._v2g_action = "idle"

    def _update_battery(self):
        if not self.is_ev:
            return
        now = time.time()
        # Temperature cycles slowly
        self.battery_temp += random.uniform(-0.5, 0.5)
        self.battery_temp = max(15.0, min(45.0, self.battery_temp))

        if self._v2g_action == "discharge" and now < self._v2g_end_time:
            discharge_kwh = V2G_POWER_KW * (HEARTBEAT_INTERVAL / 3600.0)
            soc_drop = (discharge_kwh / BATTERY_CAPACITY_KWH) * 100.0
            self.soc = max(10.0, self.soc - soc_drop)
            self.battery_temp += 0.2  # heat from discharge
        elif self._v2g_action == "charge" and now < self._v2g_end_time:
            charge_kwh = V2G_POWER_KW * (HEARTBEAT_INTERVAL / 3600.0)
            soc_rise = (charge_kwh / BATTERY_CAPACITY_KWH) * 100.0
            self.soc = min(95.0, self.soc + soc_rise)
            self.battery_temp += 0.1
        else:
            self._v2g_action = "idle"
            self.plug_status = "connected"
            # Slow self-discharge when idle
            self.soc = max(10.0, self.soc - 0.01)

        # SOH slowly degrades over time
        self.soh = max(70.0, self.soh - 0.001)

    def _update_resources(self):
        """Simulate CPU/memory/temperature drift for telemetry (Feature 1)."""
        self.cpu_usage = max(1.0, min(95.0, self.cpu_usage + random.uniform(-2, 2)))
        self.memory_usage = max(10.0, min(90.0, self.memory_usage + random.uniform(-1, 1)))
        self.temperature = max(20.0, min(85.0, self.temperature + random.uniform(-0.5, 0.5)))
        # Correlate temperature with CPU load
        if self.cpu_usage > 70:
            self.temperature += 0.5

    def _update_gps(self):
        now = time.time()
        if not self.gps_active and (now - self.start_time) >= GPS_INTERVAL:
            self.gps_active = True
            self.firmware_version = GPS_FIRMWARE_VERSION
            self.last_gps_time = now
            logger.info(f"[{self.name}] GPS activated, firmware -> {GPS_FIRMWARE_VERSION}")
        if self.gps_active and (now - self.last_gps_time) >= GPS_INTERVAL:
            self.latitude += random.uniform(-0.0005, 0.0005)
            self.longitude += random.uniform(-0.0005, 0.0005)
            self.last_gps_time = now

    async def register(self):
        payload = json.dumps({
            "device_id": self.id,
            "name": self.name,
            "firmware_version": self.firmware_version,
            "ip_address": f"10.0.0.{random.randint(1, 254)}",
            "city": self.city,
        })
        # P0 UC-25 JITP: per-device topic — broker ACL binds this topic to the
        # client cert CN, giving the backend a verified identity. The legacy
        # shared topic remains only for the anonymous demo profile.
        self._client.publish(f"iot/fleet/{self.id}/register", payload, qos=1)
        if not MQTT_TLS:
            self._client.publish("iot/fleet/register", payload, qos=1)
        self.status = "online"
        logger.info(f"[{self.name}] Registered (fw={self.firmware_version}, city={self.city})")

    async def send_heartbeat(self):
        if self._in_maintenance:
            return  # Skip heartbeats while in maintenance mode (Feature 9)
        self.uptime = min(100.0, 100.0 * (1.0 - (time.time() - self.start_time) / 86400) + 95.0)
        self.signal_strength = random.randint(max(-95, self.signal_strength - 2), min(-30, self.signal_strength + 2))
        self._update_battery()
        self._update_gps()
        self._update_resources()

        payload = {
            "uptime_percentage": round(self.uptime, 1),
            "signal_strength": self.signal_strength,
            "firmware_version": self.firmware_version,
            "city": self.city,
            "cpu_usage": round(self.cpu_usage, 1),
            "memory_usage": round(self.memory_usage, 1),
            "temperature": round(self.temperature, 1),
        }
        if self.is_ev:
            payload["soc"] = round(self.soc, 1)
            payload["soh"] = round(self.soh, 1)
            payload["battery_temp"] = round(self.battery_temp, 1)
            payload["plug_status"] = self.plug_status
        if self.gps_active:
            payload["latitude"] = round(self.latitude, 6)
            payload["longitude"] = round(self.longitude, 6)

        topic = f"iot/fleet/{self.id}/heartbeat"
        self._client.publish(topic, json.dumps(payload), qos=1)

    def connect(self, loop: asyncio.AbstractEventLoop):
        self._loop = loop
        self._client.reconnect_delay_set(min_delay=1, max_delay=60)
        if MQTT_TLS:
            import ssl
            cert_file = os.path.join(MQTT_CLIENT_CERT_DIR, f"{self.id}.crt")
            key_file = os.path.join(MQTT_CLIENT_CERT_DIR, f"{self.id}.key")
            self._client.tls_set(
                ca_certs=MQTT_CA_CERT,
                certfile=cert_file,
                keyfile=key_file,
                tls_version=ssl.PROTOCOL_TLS_CLIENT,
            )
            logger.info(f"[{self.name}] TLS enabled (cert={cert_file})")
        self._client.connect(MQTT_BROKER_HOST, MQTT_BROKER_PORT, keepalive=60)
        self._client.loop_start()

    def disconnect(self):
        self._running = False
        self._client.loop_stop()
        self._client.disconnect()

    async def register_with_retry(self, retries=3, gap=3):
        for attempt in range(retries):
            if attempt > 0:
                await asyncio.sleep(gap)
            await self.register()

    async def run(self):
        self._running = True
        self.connect(asyncio.get_event_loop())
        await self.register_with_retry()

        while self._running:
            await asyncio.sleep(HEARTBEAT_INTERVAL)
            await self.send_heartbeat()

        self.disconnect()


async def main():
    logger.info(f"Starting device simulator with {DEVICE_COUNT} devices (tls={MQTT_TLS})")
    city_list = [c.strip() for c in SIMULATOR_CITIES.split(",") if c.strip()]
    if not city_list:
        city_list = ["Bangalore"]
    logger.info(f"City pool: {city_list}, GPS interval: {GPS_INTERVAL}s")
    devices = []

    for i in range(DEVICE_COUNT):
        # P0 UC-24: in TLS mode ids must equal cert CNs (sim-001, sim-002, …).
        if i < len(SIMULATOR_DEVICE_IDS):
            device_id = SIMULATOR_DEVICE_IDS[i]
        elif MQTT_TLS:
            device_id = f"sim-{i+1:03d}"
        else:
            device_id = str(uuid.uuid4())
        is_ev = i < 3  # first 3 devices are EVs with battery simulation
        name = f"Device-{i+1:03d}"
        city = city_list[i % len(city_list)]
        device = SimulatedDevice(device_id, name, city=city, is_ev=is_ev)
        devices.append(device)
        asyncio.create_task(device.run())
        logger.info(f"Created simulated device: {name} ({device_id}) city={city} is_ev={is_ev}")

    def shutdown():
        logger.info("Shutting down simulator...")
        for d in devices:
            d.disconnect()

    loop = asyncio.get_event_loop()
    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, shutdown)
        except NotImplementedError:
            pass

    try:
        await asyncio.Event().wait()
    except asyncio.CancelledError:
        shutdown()


if __name__ == "__main__":
    asyncio.run(main())
