FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir paho-mqtt==2.1.0

COPY simulator/ ./simulator/
COPY .env.example .env

ENV PYTHONPATH=/app

CMD ["python", "-m", "simulator.simulator"]
