AEGIS_DEFAULT_SCRAPE_INTERVAL = 15
AEGIS_DEFAULT_ACTION_TIMEOUT = 30
AEGIS_DEFAULT_RETRY_MAX = 3
AEGIS_OTA_THROTTLE_DURATION_SECONDS = 300
AEGIS_HEARTBEAT_FAST_INTERVAL = 5
AEGIS_HEARTBEAT_NORMAL_INTERVAL = 10
