#!/usr/bin/env bash
# Fleet Commander — internal MQTT PKI bootstrap (P0 UC-24 / UC-25).
#
# Generates under ./certs (gitignored):
#   ca.crt / ca.key              internal CA
#   server.crt/.key              mosquitto broker cert (SAN: mosquitto, localhost)
#   fleet-backend.crt/.key       backend client cert (CN=fleet-backend)
#   simulator/sim-00N.crt/.key   per-device certs (CN=sim-00N)
#   ca.crl                       initial empty CRL (created by the backend image)
#
# Usage:  bash scripts/gen-mqtt-pki.sh [sim_count]
set -euo pipefail

SIM_COUNT="${1:-5}"
CERT_DIR="$(cd "$(dirname "$0")/.." && pwd)/certs"
SIM_DIR="$CERT_DIR/simulator"

echo "==> Generating MQTT PKI in $CERT_DIR"
mkdir -p "$SIM_DIR"

# Never overwrite an existing CA silently — unless PKI_FORCE=1 (used by CI/verify).
if [[ -f "$CERT_DIR/ca.key" ]]; then
  if [[ "${PKI_FORCE:-0}" = "1" ]]; then
    echo "PKI_FORCE=1 → wiping $CERT_DIR"
    rm -rf "$CERT_DIR"
    mkdir -p "$SIM_DIR"
  else
    echo "CA already exists ($CERT_DIR/ca.key) — delete ./certs or set PKI_FORCE=1." >&2
    exit 1
  fi
fi

gen_key() { openssl genpkey -algorithm ED25519 -out "$1" 2>/dev/null; }

# ── Internal CA ──────────────────────────────────────────────────────────────
gen_key "$CERT_DIR/ca.key"
openssl req -new -x509 -key "$CERT_DIR/ca.key" -out "$CERT_DIR/ca.crt" -days 3650 \
  -subj "/O=Fleet Commander/CN=Fleet Commander Internal CA" 2>/dev/null

# ── Broker cert ──────────────────────────────────────────────────────────────
gen_key "$CERT_DIR/server.key"
openssl req -new -key "$CERT_DIR/server.key" -out "$CERT_DIR/server.csr" \
  -subj "/O=Fleet Commander/CN=mosquitto" 2>/dev/null
openssl x509 -req -in "$CERT_DIR/server.csr" -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" \
  -CAcreateserial -out "$CERT_DIR/server.crt" -days 825 2>/dev/null \
  -extfile <(printf "subjectAltName=DNS:mosquitto,DNS:mosquitto-tls,DNS:localhost\nbasicConstraints=CA:FALSE")
rm -f "$CERT_DIR/server.csr"

# ── Backend client cert (CN = fleet-backend → ACL super-user) ───────────────
gen_key "$CERT_DIR/fleet-backend.key"
openssl req -new -key "$CERT_DIR/fleet-backend.key" -out "$CERT_DIR/backend.csr" \
  -subj "/O=Fleet Commander/CN=fleet-backend" 2>/dev/null
openssl x509 -req -in "$CERT_DIR/backend.csr" -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" \
  -CAcreateserial -out "$CERT_DIR/fleet-backend.crt" -days 825 2>/dev/null \
  -extfile <(printf "basicConstraints=CA:FALSE")
rm -f "$CERT_DIR/backend.csr"

# ── Simulator device certs (CN must equal device id) ────────────────────────
for i in $(seq 1 "$SIM_COUNT"); do
  ID=$(printf "sim-%03d" "$i")
  gen_key "$SIM_DIR/$ID.key"
  openssl req -new -key "$SIM_DIR/$ID.key" -out "$SIM_DIR/$ID.csr" \
    -subj "/O=Fleet Commander Devices/CN=$ID" 2>/dev/null
  openssl x509 -req -in "$SIM_DIR/$ID.csr" -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" \
    -CAcreateserial -out "$SIM_DIR/$ID.crt" -days 825 2>/dev/null \
    -extfile <(printf "basicConstraints=CA:FALSE")
  rm -f "$SIM_DIR/$ID.csr"
  echo "    device cert: $ID"
done

chmod 600 "$CERT_DIR"/*.key "$SIM_DIR"/*.key 2>/dev/null || true
rm -f "$CERT_DIR"/ca.srl

# ── Keep the explainer next to the keys ─────────────────────────────────────
cat > "$CERT_DIR/README.md" <<'DOCEOF'
# Fleet Commander — internal PKI (P0 UC-24 / UC-25)

Everything here is GENERATED (gitignored). Never commit private keys.
Regenerate:  bash scripts/gen-mqtt-pki.sh 5      # arg = # of device certs
Force regen: PKI_FORCE=1 bash scripts/gen-mqtt-pki.sh 5

| File | Purpose |
|---|---|
| ca.crt / ca.key | Internal CA (mosquitto trust anchor + signer) |
| server.crt / .key | Broker cert — SAN DNS:mosquitto,DNS:mosquitto-tls,DNS:localhost |
| fleet-backend.crt / .key | Backend client cert, CN=fleet-backend (ACL super-user) |
| simulator/sim-00N.crt/.key | Per-device certs — CN equals the device id |
| ca.crl | Revocation list; regenerated by POST /certs/{fp}/revoke |

After revoking:  bash scripts/reload-broker.sh   (restart broker → reload CRL)
Backend also refuses messages from revoked identities (defense-in-depth):
metric fleet_device_cert_rejected_total{reason}.
DOCEOF

# ── Initial empty CRL ────────────────────────────────────────────────────────
# Requires the cryptography package; uses the backend venv if available,
# otherwise any python with cryptography on PATH.
if command -v python >/dev/null 2>&1 && python -c "import cryptography" 2>/dev/null; then
  PY=python
elif command -v python3 >/dev/null 2>&1 && python3 -c "import cryptography" 2>/dev/null; then
  PY=python3
else
  echo "!! python+cryptography not found — run before starting production profile:" >&2
  echo "   docker compose build backend && docker compose run --rm backend \\" >&2
  echo "     python -c \"from app.pki import write_initial_crl; write_initial_crl()\"" >&2
  exit 2
fi
INTERNAL_CA_DIR="$CERT_DIR" $PY - <<'PYEOF'
# Standalone empty-CRL generator: no app imports (host may lack pydantic).
import os, datetime
from pathlib import Path
from cryptography import x509
from cryptography.hazmat.primitives import serialization

cert_dir = Path(os.environ["INTERNAL_CA_DIR"])
ca_cert = x509.load_pem_x509_certificate((cert_dir / "ca.crt").read_bytes())
ca_key = serialization.load_pem_private_key((cert_dir / "ca.key").read_bytes(), password=None)

now = datetime.datetime.now(datetime.timezone.utc)
crl = (
    x509.CertificateRevocationListBuilder()
    .issuer_name(ca_cert.subject)
    .last_update(now)
    .next_update(now + datetime.timedelta(days=30))
    .sign(ca_key, None)  # Ed25519: algorithm must be None
)
out = cert_dir / "ca.crl"
out.write_bytes(crl.public_bytes(serialization.Encoding.PEM))
print("CRL:", out)
PYEOF

echo "==> Done. certs/ is gitignored — never commit private keys."
